ARG CUDA=11.2.0

FROM nvidia/cuda:${CUDA}-cudnn8-devel-ubuntu20.04 AS on-gpu
LABEL com.kagemeka.gpu=true
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive


WORKDIR /root/

ARG PYVER=3.9

COPY py/setup.sh .
RUN \
  chmod +x setup.sh \
  && ./setup.sh \
  && rm setup.sh

COPY py/requirements.txt .
RUN \
  pip install -Ur \
  requirements.txt \
  && rm requirements.txt